name: CV checks
on:
  pull_request:
    branches: [ "main" ]
  workflow_run:
    workflows: [ "Build_PR" ]
    types:
      - completed
    branches:
      - 'pr-checks'
  workflow_dispatch: { }

jobs:
  check:
    runs-on: ubuntu-latest
    name: CV checks job
    steps:
      - uses: actions/checkout@v2
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: Build PR
          workflow_conclusion: success
          pr: ${{github.event.pull_request.number}}
      - name: Run checker
        shell: bash
        run: |
          go run ./cmd pdfcheck
      - name: Run reviewdog
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT: true
        run: |
          cat rdf.json | reviewdog -name="Streamline checks" -f=rdjson -reporter=github-check
      - name: Run reviewdog 2
        shell: bash
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNNER_PRINT_LOG_TO_STDOUT: true
        run: |-
          cat rdf.json | reviewdog -name="Streamline checks 2" -f=rdjson -reporter=github-check
